import { query, withTransaction } from "@/lib/postgres";
import { getNiboRuntimeConfig } from "./config";
import { calcularPeriodoSync } from "./dates";
import { exportNiboReport } from "./exports";
import { ensureNiboAuthenticated } from "./auth";
import { openNiboBrowser, type NiboBrowserSession } from "./browser";
import { garantirIdentificadoresExternos, prepararLinhasParaSyncNibo } from "./importer";
import { erroParaTexto, logError, logInfo } from "./logger";
import { parseNiboExportFile } from "./parser";
import type { NiboProjectConfig, NiboSyncResumo, TipoRelatorioNibo } from "./types";
import { validarArquivoExportadoNibo } from "./validator";

const TIPOS: TipoRelatorioNibo[] = ["paga", "recebida"];

async function importarLinhas(empresaId:string, linhas: Awaited<ReturnType<typeof parseNiboExportFile>>["linhas"], arquivoNome:string, runId:string, inicio:string, fim:string) {
  return withTransaction(async client => {
    const m=await client.query<{categoria_nibo:string;categoria_id:string|null}>("select categoria_nibo,categoria_id from mapeamentos where empresa_id=$1",[empresaId]);
    const mapa=new Map(m.rows.map(x=>[x.categoria_nibo.toLowerCase(),x.categoria_id]));
    const imp=await client.query<{id:string}>("insert into importacoes (empresa_id,tipo,competencia,arquivo_nome,origem,nibo_sync_run_id,periodo_inicio,periodo_fim,total_registros,valor_total,status) values ($1,$2,$3,$4,'nibo_auto',$5,$6,$7,$8,$9,'processando') returning id",[empresaId,linhas[0]?.tipo,linhas[0]?.competencia,arquivoNome,runId,inicio,fim,linhas.length,linhas.reduce((s,l)=>s+l.valor,0)]);
    let inseridos=0,atualizados=0;
    for(const l of linhas){ const exists=await client.query("select id from lancamentos where empresa_id=$1 and external_source='nibo' and external_id=$2",[empresaId,l.external_id]); const result=await client.query("insert into lancamentos (empresa_id,importacao_id,tipo,data_efetiva,competencia,descricao,categoria_nibo,categoria_id,pessoa,centro_custo,conta_bancaria,valor,hash,origem,external_source,external_id,source_content_hash) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'nibo_auto','nibo',$14,$15) on conflict (empresa_id,hash) do update set data_efetiva=excluded.data_efetiva,competencia=excluded.competencia,descricao=excluded.descricao,categoria_nibo=excluded.categoria_nibo,categoria_id=excluded.categoria_id,pessoa=excluded.pessoa,centro_custo=excluded.centro_custo,conta_bancaria=excluded.conta_bancaria,valor=excluded.valor,source_content_hash=excluded.source_content_hash",[empresaId,imp.rows[0]!.id,l.tipo,l.data_efetiva,l.competencia,l.descricao,l.categoria_nibo||null,mapa.get(l.categoria_nibo.toLowerCase())??null,l.pessoa||null,l.centro_custo||null,l.conta_bancaria||null,l.valor,l.hash,l.external_id,l.source_content_hash??null]); if(exists.rowCount) atualizados++; else inseridos++; void result; }
    await client.query("update importacoes set status='concluida',total_registros=$1 where id=$2",[inseridos,imp.rows[0]!.id]); return {inseridos,atualizados,ignorados:0};
  });
}

async function upsertState(empresaId:string,tipo:TipoRelatorioNibo,itemId:string,status:"success"|"failed",periodo?:{inicio:string;fim:string},erro?:string){ await query("insert into nibo_sync_states (empresa_id,tipo,last_attempt_at,last_successful_sync_at,last_period_start,last_period_end,status,last_error,last_run_item_id) values ($1,$2,now(),case when $4='success' then now() end,$5,$6,$4,$7,$3) on conflict (empresa_id,tipo) do update set last_attempt_at=now(),last_successful_sync_at=case when excluded.status='success' then now() else nibo_sync_states.last_successful_sync_at end,last_period_start=excluded.last_period_start,last_period_end=excluded.last_period_end,status=excluded.status,last_error=excluded.last_error,last_run_item_id=excluded.last_run_item_id",[empresaId,tipo,itemId,status,periodo?.inicio??null,periodo?.fim??null,erro??null]); }

export async function runNiboSync(triggerSource:"manual"|"scheduled"|"test") {
 const runtime=getNiboRuntimeConfig(); const configs=await query<NiboProjectConfig>("select c.empresa_id,e.nome as empresa_nome,c.nibo_company_id,c.nibo_company_name,c.sync_start_date,c.lookback_days from nibo_project_configs c join empresas e on e.id=c.empresa_id where c.nibo_enabled=true and c.auto_sync_enabled=true and e.ativo=true order by c.nibo_company_name"); const run=(await query<{id:string}>("insert into nibo_sync_runs (trigger_source,status) values ($1,'running') returning id",[triggerSource])).rows[0]!; const resumo:NiboSyncResumo={projetosTotal:configs.rows.length,projetosSucesso:0,projetosFalha:0,pagasSucesso:0,pagasFalha:0,recebidasSucesso:0,recebidasFalha:0}; let browser:NiboBrowserSession|null=null;
 try { if(!runtime.dryRun){browser=await openNiboBrowser(runtime);await ensureNiboAuthenticated(browser.page,runtime);} for(const config of configs.rows){let ok=true;for(const tipo of TIPOS){let itemId:string|undefined;try{const previous=await query<{last_successful_sync_at:string|null}>("select last_successful_sync_at from nibo_sync_states where empresa_id=$1 and tipo=$2",[config.empresa_id,tipo]);const periodo=calcularPeriodoSync({lookbackDays:config.lookback_days,lastSuccessfulSyncAt:previous.rows[0]?.last_successful_sync_at??null,syncStartDate:config.sync_start_date,initialSyncMaxDays:runtime.initialSyncMaxDays}); itemId=(await query<{id:string}>("insert into nibo_sync_items (run_id,empresa_id,tipo,nibo_company_id,nibo_company_name,periodo_inicio,periodo_fim,status) values ($1,$2,$3,$4,$5,$6,$7,'running') returning id",[run.id,config.empresa_id,tipo,config.nibo_company_id,config.nibo_company_name,periodo.inicio,periodo.fim])).rows[0]!.id; if(runtime.dryRun){await query("update nibo_sync_items set status='skipped',finished_at=now() where id=$1",[itemId]);continue;} const exported=await exportNiboReport(browser!.page,{config,tipo,periodo});const parsed=await parseNiboExportFile(exported.filePath,periodo.fim);const linhas=prepararLinhasParaSyncNibo(parsed.linhas,{config,tipo});validarArquivoExportadoNibo({...parsed,linhas},{tipo,periodoInicio:periodo.inicio,periodoFim:periodo.fim});garantirIdentificadoresExternos(linhas);const r=await importarLinhas(config.empresa_id,linhas,exported.filePath,run.id,periodo.inicio,periodo.fim);await query("update nibo_sync_items set status='success',finished_at=now(),registros_encontrados=$1,registros_inseridos=$2,registros_atualizados=$3,registros_ignorados=$4 where id=$5",[linhas.length,r.inseridos,r.atualizados,r.ignorados,itemId]);await upsertState(config.empresa_id,tipo,itemId,"success",periodo);if(tipo==='paga')resumo.pagasSucesso++;else resumo.recebidasSucesso++;}catch(e){ok=false;const erro=erroParaTexto(e);if(itemId){await query("update nibo_sync_items set status='failed',finished_at=now(),error_message=$1 where id=$2",[erro,itemId]);await upsertState(config.empresa_id,tipo,itemId,"failed",undefined,erro);}if(tipo==='paga')resumo.pagasFalha++;else resumo.recebidasFalha++;logError("nibo_sync_item_failed",{empresaId:config.empresa_id,tipo,erro});}}if(ok)resumo.projetosSucesso++;else resumo.projetosFalha++;}}finally{if(browser)await browser.close();}
 const status=resumo.projetosFalha===0?'success':resumo.projetosSucesso?'partial_success':'failed'; await query("update nibo_sync_runs set status=$1,finished_at=now(),projects_total=$2,projects_success=$3,projects_failed=$4,pagas_success=$5,pagas_failed=$6,recebidas_success=$7,recebidas_failed=$8,summary=$9::jsonb where id=$10",[status,resumo.projetosTotal,resumo.projetosSucesso,resumo.projetosFalha,resumo.pagasSucesso,resumo.pagasFalha,resumo.recebidasSucesso,resumo.recebidasFalha,JSON.stringify(resumo),run.id]);logInfo("nibo_sync_finished",{runId:run.id,...resumo});return{runId:run.id,resumo};
}
