/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalisesRouteImport } from './routes/_authenticated/analises'
import { Route as AuthenticatedAuditoriaFinanceiraRouteImport } from './routes/_authenticated/auditoria-financeira'
import { Route as AuthenticatedCustosRouteImport } from './routes/_authenticated/custos'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedDreRouteImport } from './routes/_authenticated/dre'
import { Route as AuthenticatedFluxoCaixaRouteImport } from './routes/_authenticated/fluxo-caixa'
import { Route as AuthenticatedGerenciamentoRouteImport } from './routes/_authenticated/gerenciamento'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedImportacaoRouteImport } from './routes/_authenticated/importacao'
import { Route as AuthenticatedPlanoAcaoRouteImport } from './routes/_authenticated/plano-acao'
import { Route as AuthenticatedPontoEquilibrioRouteImport } from './routes/_authenticated/ponto-equilibrio'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedReceitasRouteImport } from './routes/_authenticated/receitas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalisesRoute = AuthenticatedAnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaFinanceiraRoute =
  AuthenticatedAuditoriaFinanceiraRouteImport.update({
    id: '/auditoria-financeira',
    path: '/auditoria-financeira',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustosRoute = AuthenticatedCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDreRoute = AuthenticatedDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFluxoCaixaRoute = AuthenticatedFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerenciamentoRoute =
  AuthenticatedGerenciamentoRouteImport.update({
    id: '/gerenciamento',
    path: '/gerenciamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportacaoRoute = AuthenticatedImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanoAcaoRoute = AuthenticatedPlanoAcaoRouteImport.update({
  id: '/plano-acao',
  path: '/plano-acao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPontoEquilibrioRoute =
  AuthenticatedPontoEquilibrioRouteImport.update({
    id: '/ponto-equilibrio',
    path: '/ponto-equilibrio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceitasRoute = AuthenticatedReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analises': typeof AuthenticatedAnalisesRoute
  '/auditoria-financeira': typeof AuthenticatedAuditoriaFinanceiraRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/dre': typeof AuthenticatedDreRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/gerenciamento': typeof AuthenticatedGerenciamentoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/ponto-equilibrio': typeof AuthenticatedPontoEquilibrioRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analises': typeof AuthenticatedAnalisesRoute
  '/auditoria-financeira': typeof AuthenticatedAuditoriaFinanceiraRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/dre': typeof AuthenticatedDreRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/gerenciamento': typeof AuthenticatedGerenciamentoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/ponto-equilibrio': typeof AuthenticatedPontoEquilibrioRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analises': typeof AuthenticatedAnalisesRoute
  '/_authenticated/auditoria-financeira': typeof AuthenticatedAuditoriaFinanceiraRoute
  '/_authenticated/custos': typeof AuthenticatedCustosRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/dre': typeof AuthenticatedDreRoute
  '/_authenticated/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/_authenticated/gerenciamento': typeof AuthenticatedGerenciamentoRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/importacao': typeof AuthenticatedImportacaoRoute
  '/_authenticated/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/_authenticated/ponto-equilibrio': typeof AuthenticatedPontoEquilibrioRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/receitas': typeof AuthenticatedReceitasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analises'
    | '/auditoria-financeira'
    | '/custos'
    | '/despesas'
    | '/dre'
    | '/fluxo-caixa'
    | '/gerenciamento'
    | '/home'
    | '/importacao'
    | '/plano-acao'
    | '/ponto-equilibrio'
    | '/projetos'
    | '/receitas'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analises'
    | '/auditoria-financeira'
    | '/custos'
    | '/despesas'
    | '/dre'
    | '/fluxo-caixa'
    | '/gerenciamento'
    | '/home'
    | '/importacao'
    | '/plano-acao'
    | '/ponto-equilibrio'
    | '/projetos'
    | '/receitas'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analises'
    | '/_authenticated/auditoria-financeira'
    | '/_authenticated/custos'
    | '/_authenticated/despesas'
    | '/_authenticated/dre'
    | '/_authenticated/fluxo-caixa'
    | '/_authenticated/gerenciamento'
    | '/_authenticated/home'
    | '/_authenticated/importacao'
    | '/_authenticated/plano-acao'
    | '/_authenticated/ponto-equilibrio'
    | '/_authenticated/projetos'
    | '/_authenticated/receitas'
    | '/_authenticated/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analises': {
      id: '/_authenticated/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AuthenticatedAnalisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria-financeira': {
      id: '/_authenticated/auditoria-financeira'
      path: '/auditoria-financeira'
      fullPath: '/auditoria-financeira'
      preLoaderRoute: typeof AuthenticatedAuditoriaFinanceiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos': {
      id: '/_authenticated/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof AuthenticatedCustosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dre': {
      id: '/_authenticated/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof AuthenticatedDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo-caixa': {
      id: '/_authenticated/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerenciamento': {
      id: '/_authenticated/gerenciamento'
      path: '/gerenciamento'
      fullPath: '/gerenciamento'
      preLoaderRoute: typeof AuthenticatedGerenciamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacao': {
      id: '/_authenticated/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof AuthenticatedImportacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano-acao': {
      id: '/_authenticated/plano-acao'
      path: '/plano-acao'
      fullPath: '/plano-acao'
      preLoaderRoute: typeof AuthenticatedPlanoAcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ponto-equilibrio': {
      id: '/_authenticated/ponto-equilibrio'
      path: '/ponto-equilibrio'
      fullPath: '/ponto-equilibrio'
      preLoaderRoute: typeof AuthenticatedPontoEquilibrioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receitas': {
      id: '/_authenticated/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AuthenticatedReceitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalisesRoute: typeof AuthenticatedAnalisesRoute
  AuthenticatedAuditoriaFinanceiraRoute: typeof AuthenticatedAuditoriaFinanceiraRoute
  AuthenticatedCustosRoute: typeof AuthenticatedCustosRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedDreRoute: typeof AuthenticatedDreRoute
  AuthenticatedFluxoCaixaRoute: typeof AuthenticatedFluxoCaixaRoute
  AuthenticatedGerenciamentoRoute: typeof AuthenticatedGerenciamentoRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedImportacaoRoute: typeof AuthenticatedImportacaoRoute
  AuthenticatedPlanoAcaoRoute: typeof AuthenticatedPlanoAcaoRoute
  AuthenticatedPontoEquilibrioRoute: typeof AuthenticatedPontoEquilibrioRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedReceitasRoute: typeof AuthenticatedReceitasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalisesRoute: AuthenticatedAnalisesRoute,
  AuthenticatedAuditoriaFinanceiraRoute: AuthenticatedAuditoriaFinanceiraRoute,
  AuthenticatedCustosRoute: AuthenticatedCustosRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedDreRoute: AuthenticatedDreRoute,
  AuthenticatedFluxoCaixaRoute: AuthenticatedFluxoCaixaRoute,
  AuthenticatedGerenciamentoRoute: AuthenticatedGerenciamentoRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedImportacaoRoute: AuthenticatedImportacaoRoute,
  AuthenticatedPlanoAcaoRoute: AuthenticatedPlanoAcaoRoute,
  AuthenticatedPontoEquilibrioRoute: AuthenticatedPontoEquilibrioRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedReceitasRoute: AuthenticatedReceitasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
