// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const AUTH_REMEMBER_KEY = "vg-auth-remember";
export const AUTH_REMEMBER_UNTIL_KEY = "vg-auth-remember-until";
export const AUTH_REMEMBER_EMAIL_KEY = "vg-auth-remember-email";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function authStorage() {
  return {
    getItem(key: string) {
      const remember = localStorage.getItem(AUTH_REMEMBER_KEY);
      const until = Number(localStorage.getItem(AUTH_REMEMBER_UNTIL_KEY) ?? 0);

      if (remember === "true" && until > 0 && Date.now() > until) {
        localStorage.removeItem(key);
        sessionStorage.removeItem(key);
        localStorage.removeItem(AUTH_REMEMBER_KEY);
        localStorage.removeItem(AUTH_REMEMBER_UNTIL_KEY);
        localStorage.removeItem(AUTH_REMEMBER_EMAIL_KEY);
        return null;
      }

      if (remember === "false") {
        return sessionStorage.getItem(key);
      }

      return localStorage.getItem(key) ?? sessionStorage.getItem(key);
    },
    setItem(key: string, value: string) {
      const remember = localStorage.getItem(AUTH_REMEMBER_KEY) === "true";
      if (remember) {
        localStorage.setItem(key, value);
        sessionStorage.removeItem(key);
        return;
      }

      sessionStorage.setItem(key, value);
      localStorage.removeItem(key);
    },
    removeItem(key: string) {
      localStorage.removeItem(key);
      sessionStorage.removeItem(key);
    },
  };
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? authStorage() : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
